=== SergeyPodgayskiy/-Java01_2017-Task4/main/resources/treasure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://epam.com/treasures"
            xmlns:tns="http://epam.com/treasures"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="treasures" type="tns:Treasures"/>

    <xsd:complexType name="Treasures">
        <xsd:sequence>
            <xsd:element name="treasure" type="tns:Treasure" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Treasure">
        <xsd:choice>
            <xsd:element name="jewel" type="tns:Jewel" maxOccurs="1"/>
            <xsd:element name="ring" type="tns:Ring" maxOccurs="1"/>
            <xsd:element name="bracelet" type="tns:Bracelet" maxOccurs="1"/>
            <xsd:element name="chain" type="tns:Chain" maxOccurs="1"/>
            <xsd:element name="sandglass" type="tns:Sandglass" maxOccurs="1"/>
            <xsd:element name="beads" type="tns:Beads" maxOccurs="1"/>
            <xsd:element name="coulomb" type="tns:Coulomb" maxOccurs="1"/>
            <xsd:element name="cup" type="tns:Cup" maxOccurs="1"/>
            <xsd:element name="vase" type="tns:Vase" maxOccurs="1"/>
            <xsd:element name="statue" type="tns:Statue" maxOccurs="1"/>
            <xsd:element name="painting" type="tns:Painting" maxOccurs="1"/>
            <xsd:element name="casket" type="tns:Casket" maxOccurs="1"/>
            <xsd:element name="key" type="tns:Key" maxOccurs="1"/>
            <xsd:element name="sword" type="tns:Sword" maxOccurs="1"/>
            <xsd:element name="staff" type="tns:Staff" maxOccurs="1"/>
            <xsd:element name="mace" type="tns:Mace" maxOccurs="1"/>
            <xsd:element name="axe" type="tns:Axe" maxOccurs="1"/>
            <xsd:element name="bow" type="tns:Bow" maxOccurs="1"/>
            <xsd:element name="helmet" type="tns:Helmet" maxOccurs="1"/>
            <xsd:element name="scapular" type="tns:Scapular" maxOccurs="1"/>
            <xsd:element name="armor" type="tns:Armor" maxOccurs="1"/>
            <xsd:element name="trousers" type="tns:Trousers" maxOccurs="1"/>
            <xsd:element name="boots" type="tns:Boots" maxOccurs="1"/>
            <xsd:element name="ancient_book" type="tns:Ancient-book" maxOccurs="1"/>
            <xsd:element name="ancient_scroll" type="tns:Ancient-scroll" maxOccurs="1"/>
            <xsd:element name="magic_stone" type="tns:Magic-stone" maxOccurs="1"/>
            <xsd:element name="runic_stone" type="tns:Runic-stone" maxOccurs="1"/>
            <xsd:element name="ancient_fossil" type="tns:Ancient-fossil" maxOccurs="1"/>
            <xsd:element name="dragons_egg" type="tns:Dragons-egg" maxOccurs="1"/>
            <xsd:element name="ancient_tissue" type="tns:Ancient-tissue" maxOccurs="1"/>
            <xsd:element name="aroma" type="tns:Aroma" maxOccurs="1"/>
            <xsd:element name="princess" type="tns:Princess" maxOccurs="1"/>
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="Jewel">
        <xsd:sequence>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="diameter" type="xsd:double"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Ring">
        <xsd:sequence>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="style" type="xsd:string"/>
            <xsd:element name="hasPreciousStone" type="xsd:boolean"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Bracelet">
        <xsd:sequence>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="style" type="xsd:string"/>
            <xsd:element name="girth" type="xsd:double"/>
            <xsd:element name="hardness" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Chain">
        <xsd:sequence>
            <xsd:element name="length" type="xsd:double"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="thickness" type="xsd:double"/>
            <xsd:element name="type_of_lock" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Sandglass">
        <xsd:sequence>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="sand_type" type="xsd:string"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Beads">
        <xsd:sequence>
            <xsd:element name="length" type="xsd:double"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="thickness" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Coulomb">
        <xsd:sequence>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="form" type="xsd:string"/>
            <xsd:element name="picture" type="xsd:boolean"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Cup">
        <xsd:sequence>
            <xsd:element name="volume" type="xsd:short"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="height" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Vase">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="volume" type="xsd:double"/>
            <xsd:element name="hasPicture" type="xsd:boolean"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Statue">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="creation_date" type="xsd:string"/>
            <xsd:element name="creator" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Painting">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="creation_date" type="xsd:string"/>
            <xsd:element name="creator" type="xsd:string"/>
            <xsd:element name="quality" type="xsd:string"/>
            <xsd:element name="paint_type" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Casket">
        <xsd:sequence>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="hasLock" type="xsd:boolean"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Key">
        <xsd:sequence>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="what_open" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Sword">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="length" type="xsd:double"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="blade_thickness" type="xsd:double"/>
            <xsd:element name="damage" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Staff">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="length" type="xsd:double"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="tip_type" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Mace">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="damage" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Axe">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="type_handle" type="xsd:string"/>
            <xsd:element name="type_blade" type="xsd:string"/>
            <xsd:element name="damage" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Bow">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="arrow_type" type="xsd:string"/>
            <xsd:element name="arrow_count" type="xsd:short"/>
            <xsd:element name="damage" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Helmet">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="head_protection" type="xsd:double"/>
            <xsd:element name="head_girth" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Scapular">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="scapular_girth" type="xsd:double"/>
            <xsd:element name="body_protection" type="xsd:boolean"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Armor">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="body_protection" type="xsd:boolean"/>
            <xsd:element name="body_girth" type="xsd:double"/>
            <xsd:element name="hasPicture" type="xsd:boolean"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Trousers">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="leg_protection" type="xsd:boolean"/>
            <xsd:element name="leg_girth" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Boots">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="leg_protection" type="xsd:boolean"/>
            <xsd:element name="foot_girth" type="xsd:double"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Ancient-book">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="age" type="xsd:short"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="pages" type="xsd:short"/>
            <xsd:element name="language" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Ancient-scroll">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="age" type="xsd:short"/>
            <xsd:element name="content" type="xsd:string"/>
            <xsd:element name="school_of_magic" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Magic-stone">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="age" type="xsd:short"/>
            <xsd:element name="magic_word" type="xsd:string"/>
            <xsd:element name="translation" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Runic-stone">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="amount_rune" type="xsd:short"/>
            <xsd:element name="engraved_rune" type="xsd:string"/>
            <xsd:element name="translation" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Ancient-fossil">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="age" type="xsd:int"/>
            <xsd:element name="accessory" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Dragons-egg">
        <xsd:sequence>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="dragons_kind" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Ancient-tissue">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="size" type="xsd:double"/>
            <xsd:element name="material" type="xsd:string"/>
            <xsd:element name="hasPattern" type="xsd:boolean"/>
            <xsd:element name="pattern_type" type="xsd:string"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Aroma">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="amount" type="xsd:short"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="Princess">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="age" type="xsd:short"/>
            <xsd:element name="damnation" type="xsd:boolean"/>
            <xsd:element name="birthplace" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== SergeyPodgayskiy/-Java01_2017-Task4/main/resources/treasures.xml
<?xml version="1.0" encoding="UTF-8"?>
<treasures xmlns="http://epam.com/treasures"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://epam.com/treasures treasure.xsd">
    <treasure>
        <jewel id="11">
            <type>Precious stone</type>
            <material>Diamond</material>
            <diameter>1.2</diameter>
            <weight>0.015</weight>
            <price>324.57</price>
        </jewel>
    </treasure>
    <treasure>
        <jewel id="12">
            <type>Precious stone</type>
            <material>Ruby</material>
            <diameter>5.1</diameter>
            <weight>0.051</weight>
            <price>117</price>
        </jewel>
    </treasure>
    <treasure>
        <jewel id="13">
            <type>Halfprecious stone</type>
            <material>Opal</material>
            <diameter>35.4</diameter>
            <weight>0.156</weight>
            <price>257.3</price>
        </jewel>
    </treasure>
    <treasure>
        <ring id="21">
            <material>Gold</material>
            <weight>2.7</weight>
            <style>Classic</style>
            <hasPreciousStone>true</hasPreciousStone>
            <price>751</price>
        </ring>
    </treasure>
    <treasure>
        <ring id="22">
            <material>Platinum</material>
            <weight>6.1</weight>
            <style>Vintage</style>
            <hasPreciousStone>false</hasPreciousStone>
            <price>1024.33</price>
        </ring>
    </treasure>
    <treasure>
        <ring id="23">
            <material>Silver</material>
            <weight>5.34</weight>
            <style>Vintage</style>
            <hasPreciousStone>false</hasPreciousStone>
            <price>99.99</price>
        </ring>
    </treasure>
    <treasure>
        <bracelet id="31">
            <material>Silver</material>
            <weight>12.3</weight>
            <style>Classic</style>
            <girth>19.7</girth>
            <hardness>Hard</hardness>
            <price>230.69</price>
        </bracelet>
    </treasure>
    <treasure>
        <bracelet id="32">
            <material>Gold</material>
            <weight>13.1</weight>
            <style>Vintage</style>
            <girth>21.2</girth>
            <hardness>Medium hardness</hardness>
            <price>538.29</price>
        </bracelet>
    </treasure>
    <treasure>
        <bracelet id="33">
            <material>Steel</material>
            <weight>11.9</weight>
            <style>Classic</style>
            <girth>20.2</girth>
            <hardness>Hard</hardness>
            <price>214.99</price>
        </bracelet>
    </treasure>
    <treasure>
        <chain id="41">
            <length>0.4</length>
            <weight>0.02</weight>
            <material>Gold</material>
            <thickness>0.01</thickness>
            <type_of_lock>Springring</type_of_lock>
            <price>455</price>
        </chain>
    </treasure>
    <treasure>
        <chain id="42">
            <length>0.35</length>
            <weight>0.016</weight>
            <material>Silver</material>
            <thickness>0.01</thickness>
            <type_of_lock>Lobster</type_of_lock>
            <price>130</price>
        </chain>
    </treasure>
    <treasure>
        <chain id="43">
            <length>0.45</length>
            <weight>0.034</weight>
            <material>Gold</material>
            <thickness>0.014</thickness>
            <type_of_lock>Barrel</type_of_lock>
            <price>455</price>
        </chain>
    </treasure>
    <treasure>
        <sandglass id="51">
            <material>Steel</material>
            <sand_type>River sand</sand_type>
            <weight>14</weight>
            <price>128</price>
        </sandglass>
    </treasure>
    <treasure>
        <sandglass id="52">
            <material>Gold</material>
            <sand_type>River sand</sand_type>
            <weight>15.5</weight>
            <price>441</price>
        </sandglass>
    </treasure>
    <treasure>
        <sandglass id="53">
            <material>Platinum</material>
            <sand_type>Quarry sand</sand_type>
            <weight>13</weight>
            <price>389</price>
        </sandglass>
    </treasure>
    <treasure>
        <beads id="61">
            <length>0.35</length>
            <material>Amber</material>
            <weight>0.052</weight>
            <thickness>0.02</thickness>
            <price>205</price>
        </beads>
    </treasure>
    <treasure>
        <beads id="62">
            <length>0.55</length>
            <material>Coral</material>
            <weight>0.110</weight>
            <thickness>0.03</thickness>
            <price>336</price>
        </beads>
    </treasure>
    <treasure>
        <beads id="63">
            <length>0.40</length>
            <material>Emerald</material>
            <weight>0.210</weight>
            <thickness>0.03</thickness>
            <price>984</price>
        </beads>
    </treasure>
    <treasure>
        <coulomb id="71">
            <material>gold</material>
            <size>3.5</size>
            <weight>40</weight>
            <form>square</form>
            <picture>false</picture>
            <price>140</price>
        </coulomb>
    </treasure>
    <treasure>
        <coulomb id="72">
            <material>silver</material>
            <size>5</size>
            <weight>55</weight>
            <form>round</form>
            <picture>true</picture>
            <price>75</price>
        </coulomb>
    </treasure>
    <treasure>
        <coulomb id="73">
            <material>bronze</material>
            <size>10</size>
            <weight>40</weight>
            <form>triangle</form>
            <picture>true</picture>
            <price>30</price>
        </coulomb>
    </treasure>
    <treasure>
        <cup id="81">
            <volume>65</volume>
            <material>gold</material>
            <weight>150</weight>
            <height>70</height>
            <price>250</price>
        </cup>
    </treasure>
    <treasure>
        <cup id="82">
            <volume>25</volume>
            <material>silver</material>
            <weight>70</weight>
            <height>45</height>
            <price>100</price>
        </cup>
    </treasure>
    <treasure>
        <cup id="83">
            <volume>25</volume>
            <material>bronze</material>
            <weight>45</weight>
            <height>55</height>
            <price>85</price>
        </cup>
    </treasure>
    <treasure>
        <vase id="91">
            <title>vasel</title>
            <type>new</type>
            <volume>150</volume>
            <hasPicture>true</hasPicture>
            <price>150</price>
        </vase>
    </treasure>
    <treasure>
        <vase id="92">
            <title>lase-vase</title>
            <type>old</type>
            <volume>160</volume>
            <hasPicture>false</hasPicture>
            <price>100</price>
        </vase>
    </treasure>
    <treasure>
        <vase id="93">
            <title>grandy</title>
            <type>historical</type>
            <volume>170</volume>
            <hasPicture>true</hasPicture>
            <price>300</price>
        </vase>
    </treasure>
    <treasure>
        <statue id="101">
            <title>NY</title>
            <weight>1000</weight>
            <size>3</size>
            <type>old</type>
            <creation_date>17.11.1996</creation_date>
            <creator>Leo</creator>
            <price>700</price>
        </statue>
    </treasure>
    <treasure>
        <statue id="102">
            <title>Paris</title>
            <weight>1400</weight>
            <size>2</size>
            <type>fashion</type>
            <creation_date>15.10.2001</creation_date>
            <creator>Dicaprio</creator>
            <price>6800</price>
        </statue>
    </treasure>
    <treasure>
        <statue id="103">
            <title>Great</title>
            <weight>560</weight>
            <size>1</size>
            <type>new</type>
            <creation_date>22.07.1996</creation_date>
            <creator>Vincent</creator>
            <price>5600</price>
        </statue>
    </treasure>
    <treasure>
        <painting id="111">
            <title>Street</title>
            <type>new</type>
            <creation_date>11.11.2011</creation_date>
            <creator>Michael</creator>
            <quality>excellent</quality>
            <paint_type>goodType</paint_type>
            <price>111</price>
        </painting>
    </treasure>
    <treasure>
        <painting id="112">
            <title>Home</title>
            <type>old</type>
            <creation_date>12.12.2012</creation_date>
            <creator>Brown</creator>
            <quality>average</quality>
            <paint_type>strangeType</paint_type>
            <price>222</price>
        </painting>
    </treasure>
    <treasure>
        <painting id="113">
            <title>Adventure</title>
            <type>modern</type>
            <creation_date>13.12.2007</creation_date>
            <creator>Harry</creator>
            <quality>good</quality>
            <paint_type>amazingType</paint_type>
            <price>333</price>
        </painting>
    </treasure>
    <treasure>
        <casket id="121">
            <size>10</size>
            <weight>1.2</weight>
            <hasLock>true</hasLock>
            <price>25</price>
        </casket>
    </treasure>
    <treasure>
        <casket id="122">
            <size>12</size>
            <weight>1.8</weight>
            <hasLock>false</hasLock>
            <price>20</price>
        </casket>
    </treasure>
    <treasure>
        <casket id="123">
            <size>15</size>
            <weight>2.5</weight>
            <hasLock>true</hasLock>
            <price>35</price>
        </casket>
    </treasure>
    <treasure>
        <key id="131">
            <size>3</size>
